### ISSUE TITLE
111

### ISSUE THREAD

**Issue by kiring-may** [zhaozhiliangzzl/qshare#1]
您好，您的项目包里似乎没有sql文件，能不能附加一下

**Comment by Tang-Paofan** [comment]
sql文件是存放在云服务器的，没有本地sql

**Comment by kiring-may** [comment]
我不是很明白，其他人应该不能在自己的电脑上访问您的云sql文件吧，能不能麻烦您导入到本地，我真的挺需要的，谢谢

**Comment by zhaozhiliangzzl** [comment]
![image](https://user-images.githubusercontent.com/50540708/219061730-c5151fc9-894a-43a4-bea3-ddc93a9faa59.png)
er图给你，你可以在自己数据库中创建，
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/35457/AppData/Local/Packages/microsoft.office.desktop_8wekyb3d8bbwe/AC/%23!oice_16_974fa576_32c1d314_3945/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/35457/AppData/Local/Packages/microsoft.office.desktop_8wekyb3d8bbwe/AC/%23!oice_16_974fa576_32c1d314_3945/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/35457/AppData/Local/Packages/microsoft.office.desktop_8wekyb3d8bbwe/AC/%23!oice_16_974fa576_32c1d314_3945/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>


<div align=center>



字段名称 | 字段类型 | 字段长度 | 字段描述 | 是否主键
-- | -- | -- | -- | --
id   nickname   avatar   role   status | int   varchar   varchar   int   int | 10   20   255   2   2 | 主键   昵称   头像   用户角色   用户状态（软删除） | 是   否   否   否   否



</div>


</body>

</html>

**Comment by Tang-Paofan** [comment]
sql文件已经上传

**Comment by kiring-may** [comment]
谢谢了
